# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T08:58:55+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class HtmlPostRequest(BaseModel):
    certificateFile: Optional[bytes] = None
    privatekeyFile: Optional[bytes] = None
