# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T08:58:55+00:00

from __future__ import annotations

from typing import List

from pydantic import RootModel


class JsonGetResponse(RootModel[List[str]]):
    root: List[str]
